kind: Service
apiVersion: v1
metadata:
  name: v2ray
  namespace: jaskon139
  labels:
    app: myapp
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: v2ray
  type: ClusterIP
  sessionAffinity: None
